name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "Build & Unit Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: ./.github/workflows/build.yml@main
  codeql:
    name: "CodeQL Check"
    runs-on: "ubuntu-latest"
    needs: [build]
    steps:
      - uses: ./.github/workflows/codeql.yml@main
  release:
    needs: [build, codeql]
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: 'release-config.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: false